* Numpy bilimsel hesaplamalar, çok boyutlu arraylar ve matrisler üzerinde yüksek derecede çalışma imkanı sağlar.
* Numpy kütüphanesinin listelerden farkı verimli veri saklama ve vektörel işlemlerin yapılmasıdır.
* Numpy kütüphanesini öncelikli olarak import etmemiz gerekir.
* Daha az çabayla daha çok iş yapmayı sağlar

In [1]:
import numpy as np  # Numpy kütüphanesini import ettikten sonra as ile kullanacağımız isimleri belirledik.


In [2]:
# Klasik Python
a = [1, 2, 3, 4]
b = [2, 3, 4, 5]
ab = []

for i in range(0, len(a)):
    ab.append(a[i] * b[i])
print(ab)

[2, 6, 12, 20]


In [3]:
#Numpy
a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])
a * b

array([ 2,  6, 12, 20])

### Numpy Array'i Oluşturma (Creating Numpy Array)

Numpy arrayleri oluşturmak için np.array() fonksiyonunu kullanabiliriz.

In [4]:
print(np.array([1, 2, 3, 4, 5]))


[1 2 3 4 5]


In [5]:
print(type(np.array([1, 2, 3, 4, 5])))

<class 'numpy.ndarray'>


In [6]:
print(np.zeros(10, dtype=int))  # np.zeros() fonksiyonu ile girilen 0 kadar 0 arrayi oluşturur.


[0 0 0 0 0 0 0 0 0 0]


In [7]:
print(np.random.randint(0, 10, 10))
# np.random.randint() fonksiyonu ile başlangıç değeri ile bitiş değeri arasında istenilen adet kadar rasgele sayı oluşturur.


[9 3 2 0 0 7 1 6 9 0]


In [8]:
np.random.normal(10, 4, (3, 4))
# np.random.normal() fonksiyonu ile istenilen değerlerden oluşan normal veri oluşturur.

array([[11.44654388, 12.3944752 ,  6.70037602,  7.71066914],
       [10.89778683, 12.96267574,  7.13356894, 10.24734357],
       [13.43981016, 13.46801469,  8.29835981,  7.69770595]])

### Numpy Array Özellikleri
- Numpy arraylerinin özelliklerini öğrenmek için np.info() fonksiyonunu kullanabiliriz.
- ndim: boyut sayısı
- shape: boyut bilgisi
- size: toplam eleman sayısı
- dtype: array veri tipi


In [9]:
d = np.random.randint(10, size=5)
print(d.ndim)
print(d.shape)
print(d.size)
print(d.dtype)

1
(5,)
5
int32


### Yeniden Şekillendirme (Reshaping)

In [10]:
print(np.random.randint(1, 10, size=9))
print(np.random.randint(1, 10, size=9).reshape(3, 3))

[2 8 1 3 9 5 9 3 7]
[[2 4 6]
 [9 5 7]
 [9 3 4]]


In [11]:
ar = np.random.randint(1, 10, size=9)
print(ar.reshape(3, 3))
print(ar)

[[3 8 8]
 [6 7 1]
 [7 4 6]]
[3 8 8 6 7 1 7 4 6]


reshape() fonksiyonu ile array'in boyutlarını değiştirebiliriz.


In [12]:
x = np.random.randint(10, size=10)
print(x[0])
print(x[0:5])

2
[2 7 0 7 5]


In [13]:
x[0] = 999
print(x)

[999   7   0   7   5   6   8   5   7   9]


In [14]:
m = np.random.randint(10, size=(3, 5))
print(m)

[[4 2 0 8 1]
 [5 3 1 3 0]
 [9 2 0 4 5]]


In [15]:
print(m[0, 0])

4


In [16]:
print(m[1, 1])

3


In [17]:
m[2,3] = 999
print(m)

[[  4   2   0   8   1]
 [  5   3   1   3   0]
 [  9   2   0 999   5]]


In [18]:
m[2, 3] = 2.9
print(m)

[[4 2 0 8 1]
 [5 3 1 3 0]
 [9 2 0 2 5]]


In [19]:
print(m[:0])
print(m[1:])
print(m[0:2, 0:3])

[]
[[5 3 1 3 0]
 [9 2 0 2 5]]
[[4 2 0]
 [5 3 1]]


#### Fancy Index

In [20]:
v = np.arange(0, 30, 3)  # arange() fonksiyounu 3 parametre alır. arange(start, stop, step)

print(v[1])

3


In [21]:
print(v[4])

12


In [22]:
catch = [1, 2, 3]
print(v[catch])

[3 6 9]


### Numpy Koşullu İşlemler

In [23]:
n = np.array([1, 2, 3, 4, 5])

# 3'ten küçük olanlarını al
# Klasik döngü ile
print("Klasik Döngü")
ab = []
for i in n:
    if i < 3:
        ab.append(i)
print(ab)

Klasik Döngü
[1, 2]


In [24]:
# Numpy ile
print("Numpy")
ab = n[n < 3]
print(ab)

Numpy
[1 2]


In [25]:

print(n[n > 3])
print(n[n != 3])
print(n[n == 3])
print(n[n >= 3])

[4 5]
[1 2 4 5]
[3]
[3 4 5]


#### Matematiksel İşlemler (Mathematical Operations)

Numpy array içerisinde matematiksel işlemler yaparken n bir numpy array ise n * 2 dediğimiz zaman tüm değerleri 2 ile çarpar.


In [26]:
n = np.array([1, 2, 3, 4, 5])
print(n / 5)
print(n * 5 / 10)
print(n ** 2)
print(n - 1)

[0.2 0.4 0.6 0.8 1. ]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]
[0 1 2 3 4]


In [27]:
print(np.subtract(n, 1))  # subtract() fonksiyonu ile girilen değerleri ekiltir.
print(np.add(n, 1))  # add() fonksiyonu ile girilen değerleri ekler.
print(np.mean(n))  # mean() fonksiyonu ile girilen değerlerin ortalamasını alır.
print(np.min(n))  # min() fonksiyonu ile girilen değerlerin en küçüğünü alır.
print(np.max(n))  # max() fonksiyonu ile girilen değerlerin en büyüğünü alır.
print(np.sum(n))  # sum() fonksiyonu ile girilen değerlerin toplamını alır.
print(np.var(n))  # var() fonksiyonu ile girilen değerlerin varyansını alır.


[0 1 2 3 4]
[2 3 4 5 6]
3.0
1
5
15
2.0


In [28]:
# NumPy ile İki Bilinmeyenli Denklem Çözümü
# 5*x0 + x1 = 12
# x0 + 3*x1 = 10

a = np.array([[5, 1], [1, 3]])
b = np.array([12, 10])
print(np.linalg.solve(a, b)) # linalg.solve() fonksiyonu ile denklemi çözümler.

[1.85714286 2.71428571]
